services:
  frontend:
    build: ./sell-cart-frontend
    container_name: sell-cart-frontend
    ports:
      - "3000:3000"
    networks:
      - ecommerce-net
  
  db:
    image: postgres:latest
    container_name: sell-cart-db
    environment:
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: sell-cart-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecommerce-net

volumes:
  postgres-data:

networks:
  ecommerce-net:
    driver: bridge    
    