# build stage
FROM mcr.microsoft.com/openjdk/jdk:21-ubuntu AS build

# set working dir
WORKDIR /app

# Copy maven wrapper and pom.xml
COPY mvnw .
COPY mvnw.cmd .
COPY .mvn/ .mvn
COPY pom.xml .

# Make mvnw wrapper executable
RUN chmod +x mvnw

# download all maven depedencies
RUN ./mvnw -B dependency:go-offline

# Copy source code
COPY src ./src

# Build the app
RUN ./mvnw -B clean package -DskipTests

# --------- Server stage
FROM mcr.microsoft.com/openjdk/jdk:21-ubuntu

# server working dir
WORKDIR /app

# Copy the built jar from the build stage
COPY --from=build /app/target/*.jar app.jar

# Copy image directory
COPY images images/

EXPOSE 8080

ENTRYPOINT [ "java", "-jar", "app.jar" ]